apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubestatus
rules:
  - apiGroups:
      - ''
    resources:
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
    verbs:
      - get
      - list
